trigger:
  - main

pool:
  name: Default

steps:
  - checkout: self

  - script: |
      set -e

      echo "=== Step 1: Checking Installed Tools ==="
      docker --version
      docker compose version
    displayName: Check Server Tooling

  - script: |
      set -e

      echo "=== Step 2: Building Containers ==="
      docker compose build
    displayName: Docker Compose Build